# Generated by Django 3.2.16 on 2024-12-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(related_name='documents', to='documents.Tag'),
        ),
    ]
